# Generated by Django 5.0.5 on 2024-05-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_de',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_de',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
